apiVersion: apps/v1
kind: Deployment
metadata:
  name: gha-dockerized-k8s-website
  labels:
    app: gha-dockerized-k8s-website-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gha-dockerized-k8s-website-label
  template:
    metadata:
      labels:
        app: gha-dockerized-k8s-website-label
    spec:
      containers:
      - name: gha-dockerized-k8s-website-container
        image: datapandassandbox/application-dockerize-gha:latest
        ports:
        - containerPort: 80

--- 
apiVersion: v1
kind: Service
metadata:
  name: gha-dockerized-k8s-website-service
spec:
  type: LoadBalancer
  selector:
    app: gha-dockerized-k8s-website-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80